# Generated by Django 2.2.1 on 2019-06-01 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth', models.DateField(blank=True, null=True)),
                ('CPF', models.CharField(default='N/A', max_length=15, verbose_name='CPF')),
                ('interest', models.ManyToManyField(to='materials.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('comment', models.TextField()),
                ('analize', models.IntegerField(blank=True, choices=[(0, 'Material bem conservado'), (1, 'Responde rápido'), (2, 'Simpático')], null=True)),
                ('evaluated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated', to=settings.AUTH_USER_MODEL)),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CEP', models.CharField(max_length=15, verbose_name='CEP')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('district', models.CharField(max_length=30, verbose_name='Bairro')),
                ('street', models.CharField(max_length=140, verbose_name='Rua')),
                ('number', models.CharField(max_length=8, verbose_name='Numero')),
                ('complement', models.CharField(max_length=100, verbose_name='Complemento')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
