# Generated by Django 2.2.1 on 2019-06-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/users/avatar.png', null=True, upload_to='users', verbose_name='avatar'),
        ),
    ]
