# Generated by Django 2.2.1 on 2019-05-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='CPF',
            field=models.CharField(default='N/A', max_length=15, verbose_name='CPF'),
        ),
    ]
