# Generated by Django 2.2.1 on 2019-05-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
