# Generated by Django 2.2.1 on 2019-05-23 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Assunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('author', models.CharField(max_length=50, verbose_name='Autor')),
                ('ISBN', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('publishing_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Editora')),
                ('publication_date', models.DateField()),
                ('conservation', models.IntegerField(choices=[(0, 'NOVO'), (1, 'SEMINOVO'), (2, 'USADO'), (3, 'MUITO USADO')])),
                ('category', models.IntegerField(choices=[(0, 'LIVRO'), (1, 'TESE'), (2, 'REVISTA'), (3, 'ARTIGO'), (4, 'RESUMO'), (5, 'OUTRO')])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('subject', models.ManyToManyField(to='materials.Subject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
