# Generated by Django 2.2.1 on 2019-06-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='latitute',
            new_name='latitude',
        ),
    ]
