# Generated by Django 2.2.1 on 2019-06-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='conservation',
            field=models.IntegerField(choices=[(0, 'NOVO'), (1, 'POUCO USADO'), (2, 'USADO'), (3, 'MUITO USADO')]),
        ),
    ]
