# Generated by Django 2.2.1 on 2019-06-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20190622_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(upload_to='materials/', verbose_name='Image'),
        ),
    ]
