# Generated by Django 2.2.1 on 2019-06-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20190622_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ad',
            name='deleted_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='deleted_at',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
